[package]
name = "rust-armv7m-emu"
version = "0.1.0"
authors = ["Andrew Rachwalski <rach5000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
